#!/bin/sh
exec scala -classpath "java-server.jar" -savecompiled "$0" $@
!#

import rosrabota_test.Server

object HelloWorld {
  def main(args: Array[String]) {
	Server.main("")
  }
}

HelloWorld.main(args)